// Don't know where 'LOADING' is used
export const LOADING = 'LOADING';

export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const SET_USER = 'SET_USER';
export const UNSET_USER = 'UNSET_USER';

export const UPDATE_ALL_DATA = "UPDATE_ALL_DATA";
export const UPDATE_USER_DATA = "UPDATE_USER_DATA";
export const UPDATE_ISSUES_DATA = "UPDATE_ISSUES_DATA";
export const UPDATE_CANDIDATE_DATA = "UPDATE_CANDIDATE_DATA";
export const UPDATE_MATCHES_DATA = "UPDATE_MATCHES_DATA";
export const UPDATE_CURRENT_MATCH = "UPDATE_CURRENT_MATCH";

export const SET_MATCH_PROFILE = "SET_MATCH_PROFILE";

export const UPDATE_FOLLOWING = "UPDATE_FOLLOWING"
